volumes:
  postgres-data:

networks:
  common-net:
    driver: bridge

services:
  notification_service:
    container_name: notification-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: 1234
    networks:
      - common-net
    depends_on:
      postgres_db:
        condition: service_healthy
        
  postgres_db:
    container_name: postgres-notification-service
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nigPostgres_Pas5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - common-net